
# There are very detailed instructions for setup in the README
# Here are some additional thoughts about what is going on.

# You should be able to run all of the code that exists here if you clone the repo.

# 1. Separated into 3 different stages: fetch, process, visualize
# 2. Uses scipiper (DS R package that wraps GNU-Make) for determining
#     what has been run and exists in the shared cache or not.
# 3. viz_config.yml has mostly style stuff for the final view.
# 4. Each step has a yml with the instructions for what to run.
# 5. For GIF creation, individual frames for each timestep need to be
#     created. The instructions for each frame are automatically
#     generated by creating a task plan and new yml.
# 6. Time-specific elements of each frame will have their own function.
#     In the end, when rendering the image, the functions will be used.
# 7. The very last step will stitch all frames in the appropriate folder
#     together using ImageMagick. This step isn't super smart right now.
#     It will use any frame in the folder, so watch out if you have a
#     timestep frame that exists but is no longer in the time range. The
#     images are created/overwritten but not deleted so it could be outdated.

# Note that changing the view box will cause everything to rebuild

# You need scipiper, which means you need remake
devtools::install_github("richfitz/remake")
devtools::install_github("USGS-R/scipiper")
# You also need googledrive to push to the shared cache
install.packages("googledrive")

# Shared cache: https://drive.google.com/drive/u/0/folders/1SBEM7LDlc0G5CI9SG61uAiviSY-xvcDN

# Basic functions (after setup):

library(scipiper)

# Make sure you have all the right R stuff
remake::install_missing_packages("1_fetch.yml")
remake::install_missing_packages("2_process.yml")
remake::install_missing_packages("6_visualize.yml")

# I ran all of these fetch/process steps before today so
# it would be faster.

# Execute ALL of the fetch & process steps
scmake(remake_file = "2_process.yml")

# You will see "build" next to the steps that it has not created
#   before, sees upstream changes, or gets built each time no
#   matter what
# Otherwise you will see "OK" next to the step

# Running the "process" steps shoud not take long since I have
#   everything ready on the shared cache. The frames are not pushed
#   to the shared cache so it is up to everyone to create those
#   locally.

# Create the storm frame yml files
scmake("6_storm_gif_tasks.yml", "6_visualize.yml")

# Generate the yml for intro frames
# intro frames make the gages sweep to their sparklines
scmake("6_intro_gif_tasks.yml", "6_visualize.yml")

# Execute just one of the frames to test a style change
scmake('6_visualize/tmp/gif_TEST_frame_a_20190714_12.png', '6_storm_gif_tasks.yml')

# Make a small change and re-run (oceans are a deeper blue - #a8cced)
#   Sometimes the change isn't picked up by scipiper, and you
#   need to add force=TRUE to your scmake call
scmake('6_visualize/tmp/gif_TEST_frame_a_20190714_12.png', '6_storm_gif_tasks.yml')

# Execute complete frame, but just one
scmake('6_visualize/tmp/gif_frame_a_20190715_06.png', '6_storm_gif_tasks.yml')

# Execute all frames
# Takes less than one minute for 2019-07-14 06:00:00 to 2019-07-15 12:00:00
scmake("6_storm_gif_tasks", "6_storm_gif_tasks.yml")
scmake(remake_file = "6_intro_gif_tasks.yml")
scmake(remake_file = "6_outro_gif_frames.yml")

# Create the GIF
scmake("6_visualize/out/animation_a.gif", "6_visualize.yml")

# When you are all done, someone runs the following to push the GIF
# up to the shared cache (Google Drive)
scmake("6_visualize/out/animation_a.gif.ind", "6_visualize.yml")
