storm_code: al092017 # find the right code at https://www.nhc.noaa.gov/gis/archive_besttrack.php?year=2018
storm_name: "Harvey"
dates:
  start: '2017-08-25'
  end: '2017-09-02'
date_display_tz: 'UTC'

# view, dimensions
bbox: [-100, 22, -80, 34]
projection: "+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +a=6370997 +b=6370997 +units=m +no_defs"
height: 512
width: 1024

# styling
precip_cols: ["#FAFBF3", "#F0F8E3", "#D4E9CA", "#BBE0CE", "#B7DAD0", "#B0CCD7", "#A9B8D7", "#A297C2", "#8F6F9E", "#684A77", "#41234D"]
precip_bin: 4 # inches per bin
gage_flood_col: "#175676"
gage_norm_col: "#4BA3C3"
gage_out_col: "white"
hurricane_col: "orange"
hurricane_cols: ["#71c633", "#f4f141", "#f47c41", "#f44141", "#d63995"]
hurricane_col_names: ["Tropical Storm %s", "Hurricane %s (Cat1)", "Hurricane %s (Cat2)", "Hurricane %s (Cat3)", "Hurricane %s (Cat4)"] # If these change, legend layout may break
major_river_col: "#1874cd"
gage_river_col: "#5d9ddc"
lake_col: "#a2c7eb"
marsh_col: "#a3b7b2"
ocean_col: "#e7f1fa"
storm_line_col: "grey70"

# introductory animation
intro:
  t_last_start: 5 # last frame in the intro animation when a site should leave its lat/lon (they're staggered)
  n_frames: 20 # number of frames in the intro animation linking gages to sparklines
  elbow_radius: 50000 # radius of the curvature at the elbow of the dot travel path, in 10000ths of degrees
  point_background: "#175676"

# all animations
frame_delay_cs: 8 # delay between frames of the gif animation. cs = centiseconds = hundredths of a second

# Image placement for function calls of USGS watermark, legend, datetime, etc..
#  These are fraction of the coordinate space, where 0,0 is bottom left of figure (some stuff is right justified though - legend)
component_placement:
  watermark_x_pos: "left"
  watermark_y_pos: "top"
  datetime: # above watermark for now
    x1: 0.005
    y1: 0.85
  legend_x_pos: "left"
  legend_y_pos: "bottom"
  sparks:
    xleft: 0.85 # as percentage of figure width
    xright: 0.99 # don't use 1.0 - it causes an error (invalid value specified for graphics parameter "fig")
    ybottom: 0.01 # as percentage of figure height
    ytop: 0.99 # don't use 1.0 - it causes an error (invalid value specified for graphics parameter "fig")

ocean_name_placement:
  -
    x1: 0.5
    y1: 0.35
    label: 'Gulf of Mexico'

focus_geoms:
  - # U.S. counties
    database: county
  - # U.S. states
    database: state

secondary_geoms:
  - # non-U.S. islands
    database: "mapdata::world2Hires"
    regions: "(?!USA)"
    xlim: [275, 300]
    ylim: [16, 30]
  - # Mexico
    database: "mapdata::worldHires"
    regions: "Mexico"

cities:
  dot: # parameters for general coloring of the
    bg: "gray30"
    col: NA
    pch: 21
    cex: 1.1
  text:
    col: "gray30"
    font: 1
    cex: 1.1
    angle: 30 # angle in radians for position of label relative to dot. pos is computed from angle: 225-315=1, 315-45=4, 45-135=3, 135-225=2
    dist: 0.01 # relative (fraction of window width) distance from dot to label
  pop_min: 500000 # minimum population size of cities to be chosen by default; `custom` will make additions or modifications and `exclude` will make subtractions
  custom: # cities to add or modify relative to the maps::us.cities dataset. added cities can use lat/long from us.cities if they are present in us.cities, even if they don't meet the pop_min criterion
    -
      name: "Houston TX"
    -
      name: "Fort Worth TX"
      text_angle: 150
    -
      name: "Dallas TX"
    -
      name: "Memphis TN"
    -
      name: "San Antonio TX"
      text_angle: -180
    -
      name: "Austin TX"
      text_angle: -180
    -
      name: "Corpus Christi TX"
      dot_cex: 0.8
      text_cex: 0.8
      text_angle: -45
    -
      name: "Port Aransas TX"
      pop: 3480
      lat: 27.8333
      long: -97.0667
      dot_cex: 0.8
      text_cex: 0.8
      text_angle: 0
    -
      name: "Conroe TX"
      dot_cex: 0.8
      text_cex: 0.8
      text_angle: 170
    -
      name: "Nederland TX"
      pop: 17547
      lat: 29.973056
      long: -93.9967
      dot_cex: 0.8
      text_cex: 0.8
    -
      name: "Port Lavaca TX"
      pop: 12248
      lat: 28.6156
      long: -96.6297
      dot_cex: 0.8
      text_cex: 0.8
      text_angle: 0
    -
      name: "Rockport TX"
      pop: 8766
      lat: 28.0486
      long: -97.0411
      dot_cex: 0.8
      text_cex: 0.8
    -
      name: "Victoria TX"
      pop: 62592
      lat: 28.8169
      long: -96.9933
      dot_cex: 0.8
      text_cex: 0.8
      text_angle: 180
  exclude:
    - "Jacksonville FL"
    - "Oklahoma City OK"

# Only streamorders greater than this will be fetched.
fetch_streamorder: 5

# Only waterbodies greater than this area will be fetched.
fetch_waterbody_areasqkm: 1000

# Changes only affect river geom process step.
# Coastal threshold controls the drainage area used to limit
# flowlines that terminate at the ocean. Inland threshold
# controls the drainage area used to limit tributary flowlines
# that terminate into other flowlines.
coastal_threshold_sqkm: 1000
inland_threshold_sqkm: 40000
simplification_tolerance_m: 1000

# for linear interpolation of stage data: maximum number of hours under which
# gaps in stage data will be interpolated
stage_gap_threshold: 3
